# This is a basic workflow to help you get started with Actions

on:
#   schedule:
#     - cron: 0 0 1 * * # run monthly
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

name: Broken Link Check
jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Broken Link Check
        env:
          TARGET: https://essexlocaloffer.org.uk
          RECURSIVE: true
        uses: technote-space/broken-link-checker-action@v2
